- hosts: aws_servers
  become: yes
  tasks:
    - name: Ensure required system dependencies are installed
      dnf:
        name:
          - python3
          - python3-pip
          - git
        state: present

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
               enabled: yes

    - name: Uninstall conflicting requests package (Amazon Linux)
      dnf:
        name: python3-requests
        state: absent
      when: ansible_facts['distribution'] == 'Amazon'

    - name: Install Docker Compose using pip
      pip:
        name: docker-compose
        executable: pip3
        extra_args: "--ignore-installed"

    - name: Install Streamlit without upgrading system packages
      pip:
        name: streamlit
        executable: pip3
        extra_args: "--no-deps"
     - name: Install boto3 for DynamoDB
      pip:
        name: boto3
        executable: pip3
        extra_args: "--no-deps"
